# Generated by Django 6.0.3 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_studentprofile_user_delete_counselorprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("counselor", "Counselor"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
