# Generated by Django 6.0.3 on 2026-04-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
