services:
  django:
    # in here we build the image but in the case of the db we use aldreay exist one
    build: ./django
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: career_db
      DB_USER: career_user
      DB_PASSWORD: 786786msyt
      DB_HOST: db1
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./django:/app

    # this line say that only start django after db becuase its depnd
    depends_on:
      - db1

  db1:
    image: postgres:16
    environment:
      POSTGRES_DB: career_db
      POSTGRES_USER: career_user
      POSTGRES_PASSWORD: 786786msyt
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7

  celery:
    build: ./django # 
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./django:/app
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: career_db
      DB_USER: career_user
      DB_PASSWORD: 786786msyt
      DB_HOST: db1
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db1
      - redis

  websocket:
    build: ./websocket
    ports:
      - "8001:8001"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,websocket
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: career_db2
      DB_USER: career_user2
      DB_PASSWORD: 786786msyt2
      DB_HOST: db2
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./websocket:/app
    depends_on:
      - db2
      - redis

  db2:
    image: postgres:16
    environment:
      POSTGRES_DB: career_db2
      POSTGRES_USER: career_user2
      POSTGRES_PASSWORD: 786786msyt2
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  ai-service:
    build: ./ai-service
    ports:
      - "8002:8002"
    env_file:
      - ./ai-service/.env
    environment:
      DEBUG: "True"
      FRONTEND_ORIGIN: http://localhost:5173
      CHROMA_PERSIST_DIR: /app/chroma_db

volumes:
  postgres_data1:
  postgres_data2:
