# Generated by Django 6.0.3 on 2026-04-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0001_initial'),
        ('students', '0002_studentprofile_assigned_counselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='counselors.counselorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_reviews', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'counselor')},
            },
        ),
    ]
