# Generated by Django 6.0.3 on 2026-04-17 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0002_counselorreview'),
        ('students', '0002_studentprofile_assigned_counselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='counselors.counselorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_requests', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'counselor', 'status')},
            },
        ),
    ]
