# Generated by Django 6.0.3 on 2026-03-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CounselorProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
