# Generated by Django 6.0.3 on 2026-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapmilestone',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
