# Generated by Django 6.0.3 on 2026-04-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('roadmap', '0002_roadmapmilestone_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerroadmap',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='assessments.assessment'),
        ),
    ]
